services:
  - type: web
    name: blog-application
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/blog-application-1.0.0.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d4sclfk9c44c73ejfom0-a.virginia-postgres.render.com:5432/folongzidane
      - key: DB_USERNAME
        value: folongzidane
      - key: DB_PASSWORD
        value: p0rQM1eHDTwj3oGUKcDVez78f1YbZfbi